---
title: "Workshop3"
author: "Setareh"
date: "12/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## New Change

```{r}
library(tidyverse)
library(skimr)

survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

#write_csv(survey,file="survey_data.csv")
write_csv(survey,"survey_data.csv")

survey%>%glimpse()
survey%>%skim()

```

### Data wrangling

#### Filter

```{r}
survey%>%
  filter(country=="Australia")

survey_IT_au<-survey%>%
  filter(country=="Australia" | country=="australia"|country=="Australi")%>%
  filter(industry=="Computing or Tech" & annual_salary>80000)

survey%>%
  filter(country=="Australia" | country=="australia")

survey%>%
  filter(gender!="Men")

survey%>%
  distinct(industry)

survey%>%
  count(gender, industry, sort = TRUE)

survey_IT_au%>%add_count(highest_level_of_education_completed, sort = TRUE)
```

#### `mutate` vs `transmute`

```{r}

class(survey_IT_au$annual_salary)

survey_IT_au<-survey_IT_au %>%
  mutate(avr_salary=mean(annual_salary))

survey_IT_au%>%count(city)

survey_IT_au_grouped<-survey_IT_au%>%
  group_by(city)%>%
  mutate(max_salary=max(annual_salary))%>%
  ungroup()



survey_IT_au_grouped<-survey_IT_au %>%
  group_by(city)%>%
  mutate(max_salary=max(annual_salary))%>%
  select(how_old_are_you, job_title, city, annual_salary, avr_salary, max_salary) 


survey_IT_au%>%
  summarise(min_salary=min(annual_salary))

survey_IT_au%>%
  group_by(gender)%>%
  summarise(min_salary=min(annual_salary))

survey_IT_au%>%
  group_by(gender, city)%>%
  summarise(min_salary=min(annual_salary),
            max_salary=max(annual_salary),
            avr_salary=mean(annual_salary))%>%
  arrange(desc(avr_salary))%>%
  ungroup()

survey_IT_au<-survey_IT_au%>%
  mutate(age=parse_number(how_old_are_you))

survey_IT_au%>%
  mutate(su_analyst = case_when((job_title == "business Analyst") ~ "yes", T ~ "no"))

 ```


